services:
  django:
    container_name: kikl_django
    entrypoint: /app/entrypoint.sh
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8001:8001"
    restart: unless-stopped
